// src/achievements/catalog.ts
import { AchievementDef } from "./types";

export const ACHIEVEMENTS_CATALOG: AchievementDef[] = [
  {
    id: "first_open",
    title: "Primera parada: UVGride",
    description: "Abriste la app por primera vez. ¡Que empiece la aventura!",
    type: "binary",
    goal: 1,
    category: "Básicos",
    icon: "home-outline",
    listensTo: ["APP_OPENED"],
    counterKey: "daysActive",
  },
  {
    id: "first_favorite",
    title: "Amor a primer lugar",
    description: "Guardaste tu primer favorito. ¡Tu próximo viaje será más rápido!",
    type: "binary",
    goal: 1,
    category: "Favoritos",
    icon: "star-outline",
    listensTo: ["FAVORITE_ADDED"],
    counterKey: "favoritesCreated",
  },
  {
    id: "five_favorites",
    title: "Curador de lugares",
    description: "Ya tienes cinco favoritos. Tu mapa ahora tiene estilo propio.",
    type: "progress",
    goal: 5,
    category: "Favoritos",
    icon: "star-half-outline",
    listensTo: ["FAVORITE_ADDED"],
    counterKey: "favoritesCreated",
  },
  {
    id: "first_ride",
    title: "¡Despegue exitoso!",
    description: "Completaste tu primer viaje. ¡Buen comienzo!",
    type: "binary",
    goal: 1,
    category: "Viajes",
    icon: "airplane-outline",
    listensTo: ["RIDE_COMPLETED"],
    counterKey: "totalRides",
  },
  {
    id: "five_rides",
    title: "En ritmo de viaje",
    description: "Acumulaste cinco viajes. Ya dominas la ruta.",
    type: "progress",
    goal: 5,
    category: "Viajes",
    icon: "airplane-outline",
    listensTo: ["RIDE_COMPLETED"],
    counterKey: "totalRides",
  },
  {
    id: "first_group",
    title: "Capitán de grupo",
    description: "Creaste tu primer grupo de viaje. ¡A rodar en equipo!",
    type: "binary",
    goal: 1,
    category: "Grupos",
    icon: "people-outline",
    listensTo: ["GROUP_CREATED"],
    counterKey: "groupsCreated",
  },
  {
    id: "sos_tester",
    title: "Plan de emergencia listo",
    description: "Probaste la función SOS. Mejor prevenir que lamentar.",
    type: "binary",
    goal: 1,
    category: "Seguridad",
    icon: "alert-circle-outline",
    listensTo: ["SOS_TESTED"],
    counterKey: "sosTests",
  },
];
