version: '3.8'

services:
  backend:
    build: ./backend
    container_name: uvgride-backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - JWT_SECRET=unsecretoseguro
      - NODE_ENV=development
      - DB_NAME=uvgride
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    command: sh -c "npx wait-on tcp:database:5432 && npm start"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    restart: always

  database:
    image: postgres:15-alpine
    container_name: uvgride-database
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=uvgride
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/02-uvgride-script.sql:/docker-entrypoint-initdb.d/02-uvgride-script.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: uvgride-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - database
    restart: always

volumes:
  postgres_data:
  backend_node_modules: