services:
  backend:
    build: ./backend
    container_name: uvgride-backend
    ports:
    - "3001:3001"
    depends_on:
    - database
    environment:
    - NODE_ENV=development
    - DB_NAME=uvgride
    - DB_USER=postgres
    - DB_PASSWORD=password
    - DB_HOST=database
    - DB_PORT=5432
    command: sh -c "npx wait-on tcp:database:5432 && npm start"
    volumes:
    - ./backend:/app
    - backend_node_modules:/app/node_modules
    restart: always

  frontend:
    build: ./frontend
    container_name: uvgride-frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=190.56.194.12
    restart: always
    command: npm start

  database:
    image: postgres:15-alpine
    container_name: uvgride-database
    ports:
      - "15432:5432"  # Cambiado para no chocar con postgres local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=uvgride
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/02-uvgride-script.sql:/docker-entrypoint-initdb.d/02-uvgride-script.sql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: uvgride-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - database
    restart: always

volumes:
  postgres_data:
  backend_node_modules:
  frontend_node_modules: